export const tour_packages = [
  {
    id: 1,
    image: "/images/tour-package/srilanka/15499.webp",
    title: "Sigiriya • Kandy • Colombo",
    category: "srilanka",
    price: "43,500",
    rating: 5,
    duration: "5 Days & 4 Nights",
    description: {
      details:
        "Sri Lanka is a land of lush jungles, golden beaches, and ancient wonders. From the legendary rock fortress of Sigiriya to the cultural charm of Kandy and the vibrant city vibes of Colombo, this curated trip lets you experience the magical essence of the island in just five unforgettable days.Perfect for cultural travelers, nature lovers, and explorers seeking a unique South Asian adventure!",
      tripIncludes: [
        "🏨 4 Nights Hotel Accommodation (Standard 3–4 Star)",
        "🚐 Inter-City Transfers & Sightseeing Transport",
        "🧭 Guided Tours:",
        " Sigiriya Rock Fortress",
        " Temple of the Tooth – Kandy",
        " Colombo City Highlights (Independence Square, Galle Face, etc.)",
        "🍽️ Daily Breakfast Included",
        "🧳 Luggage Handling",
        "👨‍✈️ Local English-Speaking Guide",
      ],
      additionalInfo: [
        "✈️ Airfare Not Included (Available Upon Request)",
        "🛂 Visa Assistance Provided",
        "🍛 Lunch & Dinner Excluded",
        "👥 Twin Sharing Accommodation",
        "📦 EMI Option Available",
      ],
    },
    additionalInfo: [
      "✅ Original Passport Minimum 7 Months Validity.",
      "✅ 48mm x 33mm, 1 Copy Photo. (May vary based on Nation)",
      "✅ Bank statement and solvency certificate for last 6 months. Balance Minimum BDT. 3,00,000/- .",
      "✅ NOC for Service Holder.",
      "✅ Office ID card for Job Holder.",
      "✅ Confirmed Air Ticket",
    ],
  },
  {
    id: 10,
    image:
      "/images/tour-package/bangladesh/481065103_122191915988252080_6829313308768125114_n.webp",
    title: "Sylhet",
    category: "bangladesh",
    price: "1,399",
    rating: 5,
    duration: "2 Days & 3 Nights",
    description: {
      details:
        "Dive into the emerald landscapes of Sylhet where rolling tea gardens, rocky rivers, and misty hills create a perfect escape for nature lovers. This short yet soulful tour is ideal for travelers seeking serenity, local flavors, and offbeat adventures. From the calming flow of the Dawki border streams to the lush green trails of Jaflong, every stop in Sylhet promises refreshing peace and pristine beauty.Whether you're strolling by the boulder-filled rivers of Bichanakandi or sipping fresh tea in the hilly estates of Srimangal, this trip is a breath of fresh air in every sense.",
      tripIncludes: [
        "🌃 3 Nights Hotel Accommodation (Clean & Comfortable)",
        "🚐 All Local Transfers & Tour Transportation",
        "🗣 English & Bengali Speaking Tour Guide",
        "📷 Complimentary Group Photography",
        "📞 24/7 Emergency Contact Support",
        "📄 Pre-Trip Tips & Itinerary Planning",
      ],
      additionalInfo: [
        "Booking Confirmation provided within 24 hours",
        "Group & Private Packages Available",
        "Wheelchair/Accessibility Support (upon request)",
        "Light Packing Recommended (backpack style)",
        "Tour Starts Early Morning on Day 1 — Arrive at meeting point 30 minutes prior",
        "Refund Policy: Based on T&C of Royal Safari Tours",
      ],
    },
    additionalInfo: [
      "🔘 Call: 01898-334722 / 01898-334733",
      "📧 Email: info.royalsafaritours@gmail.com",
      "📍 Office: Khilgaon, Dhaka",
      "🌐 Facebook",
    ],
  },
  {
    id: 16,
    image:
      "/images/tour-package/nepal/533477126_122223586562252080_3825507708987867031_n.webp",
    title: "Kathmundu",
    category: "nepal",
    price: "16,500",
    rating: 5,
    duration: "4 Days & 3 Nights",
    description: {
      details:
        "Experience the serene beauty of Nepal with this smart-budget yet unforgettable package! Explore the vibrant city of Kathmandu, with its rich culture, spiritual heritage, and breathtaking mountain views all without breaking the bank.Perfect for first-time travelers, adventure seekers, and spiritual explorers!",
      tripIncludes: [
        "🚐 Airport/Hotel Transfers",
        "🏨 3 Nights Hotel Accommodation",
        "🍳 Daily Breakfast at Hotel",
        "🧭 Sightseeing Assistance",
        "📍 Top Attractions (Boudhanath, Pashupatinath & More)",
        "🧳 Luggage Handling Support",
        "🎒 Free Travel Tips & Local Guidance",
      ],
      additionalInfo: [
        "✈️ Flight Not Included (Can Be Arranged Separately)",
        "🛂 No Visa Required for Bangladeshi Passport Holders",
        "🧍 Twin Sharing Basis",
        "📦 EMI Installments Available",
        "📸 Travel Photography Optional (Add-on)",
      ],
    },
    additionalInfo: [
      "✅ Original Passport Minimum 7 Months Validity.",
      "✅ 48mm x 33mm, 1 Copy Photo. (May vary based on Nation)",
      "✅ Bank statement and solvency certificate for last 6 months. Balance Minimum BDT. 3,00,000/- .",
      "✅ NOC for Service Holder.",
      "✅ Office ID card for Job Holder.",
      "✅ Confirmed Air Ticket",
    ],
  },

  {
    id: 13,
    image:
      "/images/tour-package/maldives/517477144_122217205388252080_7421407302023780902_n.webp",
    title: "Hotel Combo: Marina + Avoca Inn",
    category: "maldives",
    price: "27,900",
    rating: 5,
    duration: "4 Days & 3 Nights",
    description: {
      details:
        "Experience the serene beauty of the Maldives — turquoise waters, overwater villas, and white sandy beaches. This exclusive getaway offers both premium overwater living and budget island comfort, all bundled into one perfectly curated escape.Perfect for honeymooners, couples, and dreamers looking for peace and paradise!",
      tripIncludes: [
        "🏨 Accommodation:",
        " 2 Nights at Hard Rock Resort (Silver Sky Studio)",
        " 1 Night at Adaaran Inn (Deluxe Room)",
        "🚤 Speedboat Transfer from Airport",
        "🚗 Island Car Transfers",
        "🍽️ Daily Breakfast Included",
        "🛶 Padel Boat Adventure",
        "📸 Complimentary Beach Photography",
        "🧭 Resort Coordination Support",
      ],
      additionalInfo: [
        "✈️ Flights Not Included",
        "🛂 Visa On Arrival (For Bangladeshi Passport Holders)",
        "👥 Twin Sharing Accommodation",
        "💼 Luggage Handling",
        "📦 EMI Support Available",
      ],
    },
    additionalInfo: [
      "✅ Original Passport Minimum 7 Months Validity.",
      "✅ 48mm x 33mm, 1 Copy Photo. (May vary based on Nation)",
      "✅ Bank statement and solvency certificate for last 6 months. Balance Minimum BDT. 3,00,000/- .",
      "✅ NOC for Service Holder.",
      "✅ Office ID card for Job Holder.",
      "✅ Confirmed Air Ticket",
    ],
  },
  {
    id: 4,
    image: "/images/tour-package/srilanka/15500.webp",
    title: "Kandy • Nuwara Eliya • Ella • Colombo",
    category: "srilanka",
    price: "43,900",
    rating: 5,
    duration: "7 Days & 6 Nights",
    description: {
      details:
        "Embark on an unforgettable journey through the misty hills, emerald tea gardens, and serene waterfalls of Sri Lanka. From the sacred city of Kandy to the scenic train rides of Ella and the cosmopolitan energy of Colombo — this is the ultimate nature and culture fusion tour!Perfect for backpackers, travel vloggers, couples, and offbeat explorers who crave a deeper Sri Lankan experience.",
      tripIncludes: [
        "🏨 6 Nights Hotel Accommodation (3–4 Star Selection)",
        "🚆 Iconic Ella Train Ride (Kandy to Ella)",
        "🚐 All Inter-City Transfers with Scenic Stops",
        "🧭 Guided Exploration of:",
        " • Kandy Cultural Sites",
        " • Tea Estates of Nuwara Eliya",
        " • Ella Rock Viewpoints & Nine Arches Bridge",
        " • Colombo City Life",
        "🍽️ Daily Breakfast Included",
        "🧳 Porter & Luggage Support",
        "👨‍✈️ Local English-Speaking Tour Guide",
      ],
      additionalInfo: [
        "✈️ Airfare Not Included (Add-on Option Available)",
        "🛂 Visa Support Provided",
        "🍛 Lunch & Dinner Not Included",
        "👥 Twin Sharing Basis",
        "📦 EMI Option Available",
      ],
    },
    additionalInfo: [
      "✅ Original Passport Minimum 7 Months Validity.",
      "✅ 48mm x 33mm, 1 Copy Photo. (May vary based on Nation)",
      "✅ Bank statement and solvency certificate for last 6 months. Balance Minimum BDT. 3,00,000/- .",
      "✅ NOC for Service Holder.",
      "✅ Office ID card for Job Holder.",
      "✅ Confirmed Air Ticket",
    ],
  },
  {
    id: 23,
    image:
      "/images/tour-package/thailand/498128270_122208163508252080_1043866001400738660_n.webp",
    title: "Bangkok, Pattaya, Coral Island",
    category: "thailand",
    price: "69,900",
    rating: 5,
    duration: "4 Days & 5 Nights",
    description: {
      details:
        "A 4 day- 5 night group tour in the most exotic places in Thailand.Ideal for Family group Tours",
      tripIncludes: [
        "🏙️ Explore vibrant Bangkok",
        "🏖️ Beach escape in Pattaya",
        "🌊 Coral Island speedboat trip",
        "🛍️ Thai market tour & shopping",
        "⛩️ Temples & cultural landmarks",
      ],
      additionalInfo: [
        "✍️ Advance Required: ৳30,000",
        "🔁 70% Refundable before 15 days",
        "📜 Passport validity must be 6+ months",
      ],
    },
    additionalInfo: [
      "✅ Original Passport Minimum 7 Months Validity.",
      "✅ 48mm x 33mm, 1 Copy Photo. (May vary based on Nation)",
      "✅ Bank statement and solvency certificate for last 6 months. Balance Minimum BDT. 3,00,000/- .",
      "✅ NOC for Service Holder.",
      "✅ Office ID card for Job Holder.",
      "✅ Confirmed Air Ticket",
    ],
  },
  {
    id: 5,
    image: "/images/tour-package/srilanka/15501.webp",
    title: "Kandy • Nuwara Eliya • Benta • Colombo",
    category: "srilanka",
    price: "49,900",
    rating: 5,
    duration: "6 Days & 7 Nights",
    description: {
      details:
        "Journey through the lush green heart of Sri Lanka aboard one of the world’s most breathtaking train routes. This tour is designed for those who want to soak in nature’s splendor — from misty mountains and tea plantations to cultural temples and vibrant cityscapes. Ideal for couples, photographers, and slow travelers.",
      tripIncludes: [
        "🚆 Reserved Seat on the Famous Ella Scenic Train",
        "🏨 6 Nights Accommodation (3–4 Star Hotels)",
        "🚐 Private Transfers Between All Destinations",
        "🕌 Visits to:",
        " • Temple of the Tooth – Kandy",
        " • Gregory Lake – Nuwara Eliya",
        " • Nine Arches Bridge – Ella",
        " • Colombo City Tour",
        "🍽️ Daily Breakfast Included",
        "🧳 Porter Assistance + Local Travel Tips",
        "🧭 English-Speaking Local Guide",
      ],
      additionalInfo: [
        "✈️ Airfare Not Included (Optional Add-on Available)",
        "👥 Twin Sharing Room",
        "🍱 Lunch/Dinner at Own Expense",
        "🛂 Visa Processing Assistance Included",
        "📦 EMI Available on Request",
      ],
    },
    additionalInfo: [
      "✅ Original Passport Minimum 7 Months Validity.",
      "✅ 48mm x 33mm, 1 Copy Photo. (May vary based on Nation)",
      "✅ Bank statement and solvency certificate for last 6 months. Balance Minimum BDT. 3,00,000/- .",
      "✅ NOC for Service Holder.",
      "✅ Office ID card for Job Holder.",
      "✅ Confirmed Air Ticket",
    ],
  },
  {
    id: 6,
    image: "/images/tour-package/srilanka/15502.webp",
    title: "Kandy • Ella",
    category: "srilanka",
    price: "31,900",
    rating: 5,
    duration: "4 Days & 3 Nights",
    description: {
      details:
        "Short on time but big on adventure? This express Sri Lanka tour lets you experience the highlights in just a few days. Ride the scenic train from Kandy to Ella, explore lush mountains, waterfalls, tea plantations, and historic sites — all bundled in a well-paced itinerary perfect for quick explorers and budget travelers.",
      tripIncludes: [
        "🚆 Train Ride from Kandy to Ella",
        "🏨 4 Nights Accommodation (Comfortable Category Hotels)",
        "🚐 Intercity Private Transfers",
        "🕌 Sightseeing Highlights:",
        " • Kandy Lake & Temple of the Tooth",
        " • Ella Gap, Nine Arches Bridge",
        " • Little Adam’s Peak",
        "🍽️ Daily Breakfast",
        "🧭 Local English-Speaking Tour Coordinator",
        "🧳 Luggage Handling",
      ],
      additionalInfo: [
        "✈️ Flights Not Included",
        "🛂 Visa Support Included",
        "👥 Twin Sharing Basis",
        "📦 EMI Available",
        "🛏️ Budget & Standard Hotel Options",
      ],
    },
    additionalInfo: [
      "✅ Original Passport Minimum 7 Months Validity.",
      "✅ 48mm x 33mm, 1 Copy Photo. (May vary based on Nation)",
      "✅ Bank statement and solvency certificate for last 6 months. Balance Minimum BDT. 3,00,000/- .",
      "✅ NOC for Service Holder.",
      "✅ Office ID card for Job Holder.",
      "✅ Confirmed Air Ticket",
    ],
  },
  {
    id: 7,
    image:
      "/images/tour-package/bangladesh/476963727_122187918482252080_5424159072217857174_n.webp",
    title: "sajek valley",
    category: "bangladesh",
    price: "3,499",
    rating: 5,
    duration: "2 Days & 3 Nights",
    description: {
      details:
        "Embark on a breathtaking journey to Sajek Valley , the iconic “Land of Clouds” nestled high in the hills of Rangamati. Famous for its rolling mist, endless green ridges, and wooden cottages perched on hilltops, Sajek is a dream come true for nature lovers, couples, and photographers alike.This 2-day, 3-night adventure offers a peaceful break from city life , waking up above the clouds, sipping tea with panoramic views, and riding through winding mountain roads surrounded by silence and serenity.",
      tripIncludes: [
        "🏡 3 Nights Comfortable Hilltop Stay",
        "🚙 All Transfers (Dhaka–Sajek–Dhaka + Local Jeep Transfers)",
        "🗣 Bengali-Speaking Local Tour Guide",
        "📷 Group Photo Session in Scenic Spots",
        "📞 24/7 On-Tour Emergency Support",
        "🗺 Personalized Sightseeing Itinerary (Helipad, Konglak Hill, Ruilui Para)",
      ],
      additionalInfo: [
        "Confirmation within 24 Hours of Booking",
        "Light Bag Recommended (Backpack-style)",
        "No WiFi – Ideal for Digital Detox",
        "Electricity Availability May Vary – Powerbanks Advised",
        "Not Suitable for Elderly with Mobility Restrictions",
        "Ideal for Couples, Friends, & Adventure Groups",
      ],
    },
    additionalInfo: [
      "🔘 Call: 01898-334722 / 01898-334733",
      "📧 Email: info.royalsafaritours@gmail.com",
      "📍 Office: Khilgaon, Dhaka",
      "🌐 Facebook",
    ],
  },
  {
    id: 8,
    image:
      "/images/tour-package/bangladesh/476978831_122187919274252080_7383935039835532059_n.webp",
    title: "rangamati",
    category: "bangladesh",
    price: "14,99",
    rating: 5,
    duration: "1 Days & 2 Nights",
    description: {
      details:
        "Journey into the peaceful hills of Rangamati  a destination where emerald green lakes, tribal culture, and untouched forests harmoniously blend together. From a tranquil boat ride on Kaptai Lake to exploring hanging bridges and lakeside pagodas, this quick getaway is your perfect nature retreat. Ideal for a weekend recharge, Rangamati offers the calm you didn’t know you needed. With the scent of the forest, sound of tribal drums, and boat rides through crystal waters, it’s a short trip with deep memories.",
      tripIncludes: [
        "🏨 2 Nights Stay in a Lakeside Hotel",
        "🚐 AC Transport: Dhaka ↔ Rangamati",
        "🚤 Scenic Boat Ride on Kaptai Lake",
        "🗣 Friendly Local Tour Guide",
        "📸 Complimentary Group Photos",
        "☎️ 24/7 Helpline Assistance During Trip",
        "🧭 Visit to Hanging Bridge, Chakma Rajbari, DC Bungalow Area",
      ],
      additionalInfo: [
        "Booking Confirmation within 24 hours",
        "Light Backpack Advised",
        "Suitable for Families, Couples, and Friends",
        "Entry Tickets Not Included",
        "Tour Starts Thursday Night – Returns Saturday",
      ],
    },
    additionalInfo: [
      "🔘 Call: 01898-334722 / 01898-334733",
      "📧 Email: info.royalsafaritours@gmail.com",
      "📍 Office: Khilgaon, Dhaka",
      "🌐 Facebook",
    ],
  },
  {
    id: 3,
    image: "/images/tour-package/srilanka/15497.webp",
    title: "Colombo • Bentota",
    category: "srilanka",
    price: "48,900",
    rating: 5,
    duration: "6 Days & 5 Nights",
    description: {
      details:
        "Looking for a peaceful escape with a mix of coastal charm and urban elegance? This Sri Lanka package is designed to help you unwind along the pristine beaches of Bentota and explore the vibrant capital city of Colombo. Ideal for couples, honeymooners, and slow travelers who want to relax and recharge.",
      tripIncludes: [
        "🏨 4 Nights Stay in 3–4 Star Hotels",
        "🚐 Airport Transfers + Private City Transfers",
        "🏖️ Bentota Beach Day with Leisure Time",
        "🌆 Colombo City Tour (Galle Face, Independence Square, Local Markets)",
        "🍽️ Daily Breakfast Included",
        "🧭 Local English-Speaking Guide",
        "📸 Optional Photography Add-on",
        "🧳 Luggage Handling Service",
      ],
      additionalInfo: [
        "✈️ Flights Not Included",
        "🛂 Visa Support Included",
        "👥 Twin Sharing Accommodation",
        "🛏️ Seaview Room Upgrade Available (Extra Charge)",
        "📦 EMI Facility Available",
      ],
    },
    additionalInfo: [
      "✅ Original Passport Minimum 7 Months Validity.",
      "✅ 48mm x 33mm, 1 Copy Photo. (May vary based on Nation)",
      "✅ Bank statement and solvency certificate for last 6 months. Balance Minimum BDT. 3,00,000/- .",
      "✅ NOC for Service Holder.",
      "✅ Office ID card for Job Holder.",
      "✅ Confirmed Air Ticket",
    ],
  },
  {
    id: 9,
    image:
      "/images/tour-package/bangladesh/480744463_122191439930252080_7873249508093929957_n.webp",
    title: "cox's bazar",
    category: "bangladesh",
    price: "2,999",
    rating: 5,
    duration: "2 Days & 3 Nights",
    description: {
      details:
        "Breathe in the salty breeze and feel the soft sands under your feet as you unwind on the world’s longest natural sea beach  Cox’s Bazar. From golden sunsets to lively beachside cafes, this coastal getaway brings together adventure, peace, and fun like no other.Whether you're walking along Laboni Point, exploring Himchori Waterfall, or enjoying fresh seafood at Kolatoli Beach, Cox's Bazar gives you the ultimate tropical escape — just a few hours away from the city chaos.",
      tripIncludes: [
        "🏨 Premium Hotel Stay (3 Nights)",
        "🚌 AC Transport: Dhaka ↔ Cox’s Bazar",
        "🌅 Guided Sunrise Beach Walk",
        "📸 Complimentary Trip Photography",
        "🗣 Experienced Tour Guide",
        "🐚 Beach Activities (Beach Ball, Frisbee, etc.)",
        "🚐 Sightseeing Tour to Inani Beach & Himchori",
      ],
      additionalInfo: [
        "Confirmation Upon Booking",
        "Family & Couple Friendly",
        "Light Baggage Preferred",
        "Safe for All Age Groups",
        "EMI Available on Request",
      ],
    },
    additionalInfo: [
      "🔘 Call: 01898-334722 / 01898-334733",
      "📧 Email: info.royalsafaritours@gmail.com",
      "📍 Office: Khilgaon, Dhaka",
      "🌐 Facebook",
    ],
  },

  {
    id: 12,
    image:
      "/images/tour-package/maldives/516873867_122217205394252080_5106339833138535035_n.webp",
    title: "Hard Rock Resort",
    category: "maldives",
    price: "78,900",
    rating: 5,
    duration: "4 Days & 3 Nights",
    description: {
      details:
        "Experience the serene beauty of the Maldives — turquoise waters, overwater villas, and white sandy beaches. This exclusive getaway offers both premium overwater living and budget island comfort, all bundled into one perfectly curated escape.Perfect for honeymooners, couples, and dreamers looking for peace and paradise!",
      tripIncludes: [
        "🏨 Accommodation:",
        " 2 Nights at Hard Rock Resort (Silver Sky Studio)",
        " 1 Night at Adaaran Inn (Deluxe Room)",
        "🚤 Speedboat Transfer from Airport",
        "🚗 Island Car Transfers",
        "🍽️ Daily Breakfast Included",
        "🛶 Padel Boat Adventure",
        "📸 Complimentary Beach Photography",
        "🧭 Resort Coordination Support",
      ],
      additionalInfo: [
        "✈️ Flights Not Included",
        "🛂 Visa On Arrival (For Bangladeshi Passport Holders)",
        "👥 Twin Sharing Accommodation",
        "💼 Luggage Handling",
        "📦 EMI Support Available",
      ],
    },
    additionalInfo: [
      "✅ Original Passport Minimum 7 Months Validity.",
      "✅ 48mm x 33mm, 1 Copy Photo. (May vary based on Nation)",
      "✅ Bank statement and solvency certificate for last 6 months. Balance Minimum BDT. 3,00,000/- .",
      "✅ NOC for Service Holder.",
      "✅ Office ID card for Job Holder.",
      "✅ Confirmed Air Ticket",
    ],
  },

  {
    id: 14,
    image:
      "/images/tour-package/maldives/517673337_122217205376252080_1014846706217480811_n.webp",
    title: "San Siyam + Avoca Inn Combo",
    category: "maldives",
    price: "66,900",
    rating: 5,
    duration: "4 Days & 3 Nights",
    description: {
      details:
        "Why just dream of the Maldives when you can wake up to paradise?This premium combo package is crafted for travelers who want a slice of luxury with affordability — featuring overwater-style beach villas and local charm in a scenic, tropical setting.",
      tripIncludes: [
        "🏨 Accommodation:",
        " 2 Nights at San Siyam Olhuveli – Beach Pavilion Room",
        " 1 Night at Avoca Inn – Deluxe Room",
        "🚤 Speedboat Transfers",
        "🚗 Car Transfers",
        "🍽️ Daily Breakfast",
        "🌅 Scenic Island Views",
      ],
      additionalInfo: [
        "✈️ Airfare not included",
        "📄 Visa on Arrival for Bangladeshi Passport",
        "👥 Twin Sharing Basis",
        "📦 EMI Support Available",
      ],
    },
    additionalInfo: [
      "✅ Original Passport Minimum 7 Months Validity.",
      "✅ 48mm x 33mm, 1 Copy Photo. (May vary based on Nation)",
      "✅ Bank statement and solvency certificate for last 6 months. Balance Minimum BDT. 3,00,000/- .",
      "✅ NOC for Service Holder.",
      "✅ Office ID card for Job Holder.",
      "✅ Confirmed Air Ticket",
    ],
  },
  {
    id: 15,
    image:
      "/images/tour-package/maldives/517683948_122217205382252080_6439145938118167480_n.webp",
    title: "Fihalhohi Island Resort Hotel, Crystal Sands Hotel",
    category: "maldives",
    price: "56,900",
    rating: 5,
    duration: "4 Days & 3 Nights",
    description: {
      details:
        "Looking for a touch of luxury and serenity at once? This value-packed package is your chance to experience both resort life and local island charm in a single trip — visa, hotel, transfers, and breakfast — all included!",
      tripIncludes: [
        "2 Nights at Fihalhohi Island Resort Hotel – Deluxe Sky / Beach Room",
        "1 Night at Crystal Sands Hotel – Sea View Room (with Balcony)",
        "🚤 Speedboat Transfer",
        "🚗 Car Transfer",
        "🍽️ Daily Breakfast",
      ],
      additionalInfo: [
        "📄 Visa on Arrival for Bangladeshi Passport",
        "👤 Twin Sharing Basis",
        "📦 EMI Support Available",
        "📸 Ideal for: Honeymooners, Island Lovers, or Mini Escapes",
      ],
    },
    additionalInfo: [
      "✅ Original Passport Minimum 7 Months Validity.",
      "✅ 48mm x 33mm, 1 Copy Photo. (May vary based on Nation)",
      "✅ Bank statement and solvency certificate for last 6 months. Balance Minimum BDT. 3,00,000/- .",
      "✅ NOC for Service Holder.",
      "✅ Office ID card for Job Holder.",
      "✅ Confirmed Air Ticket",
    ],
  },
  {
    id: 2,
    image: "/images/tour-package/srilanka/15498.webp",
    title: "Negombo • Wilpattu",
    category: "srilanka",
    price: "32,900",
    rating: 5,
    priceOff: "2500",
    duration: "3 Days & 2 Nights",
    description: {
      details:
        "This short yet thrilling Sri Lanka getaway is crafted for wildlife lovers and nature enthusiasts. Experience the vast wilderness of Wilpattu National Park – home to leopards, elephants, and exotic birds – combined with the coastal charm of Negombo.",
      tripIncludes: [
        "🏨 2 Nights Hotel Stay (Standard to 3-Star)",
        "🚙 Private Vehicle Transfers",
        "🐾 Full-Day Jeep Safari in Wilpattu",
        "🌴 Evening Leisure Time in Negombo",
        "🍽️ Daily Breakfast Included",
        "🧭 English-Speaking Safari Guide",
        "📸 Wildlife Photography Support",
        "🧳 All Entry Fees Covered",
      ],
      additionalInfo: [
        "✈️ Flights Not Included",
        "🛂 Visa Support Available",
        "👥 Twin Sharing Accommodation",
        "🦺 Safety Measures During Safari",
        "📦 EMI Option Available",
      ],
    },
    additionalInfo: [
      "✅ Original Passport Minimum 7 Months Validity.",
      "✅ 48mm x 33mm, 1 Copy Photo. (May vary based on Nation)",
      "✅ Bank statement and solvency certificate for last 6 months. Balance Minimum BDT. 3,00,000/- .",
      "✅ NOC for Service Holder.",
      "✅ Office ID card for Job Holder.",
      "✅ Confirmed Air Ticket",
    ],
  },

  {
    id: 11,
    image:
      "/images/tour-package/bangladesh/481268799_122192379224252080_8541591813321427625_n.webp",
    title: "sundarban",
    category: "bangladesh",
    price: "22,000",
    rating: 5,
    duration: "3 Days & 2 Nights",
    description: {
      details:
        "Experience the raw, untouched beauty of the world’s largest mangrove forest  The Sundarbans. From cruising along mysterious forest rivers to spotting rare wildlife like the Royal Bengal Tiger, this immersive 3-day journey is a dream for nature lovers.Specially curated, this luxury package blends comfort, adventure, and serenity. Float through the creeks, sleep aboard a houseboat, and wake to the sounds of wild nature. This is not just a tour it’s a once-in-a-lifetime experience.",
      tripIncludes: [
        "🛳️ Luxury Houseboat Stay (2 Nights, AC Cabin)",
        "🦜 Guided Wildlife Safari (Karamjol, Kotka, Harbaria)",
        "🍛 Full Board Meal Plan (Breakfast, Lunch, Dinner, Tea)",
        "🧭 Forest Entry & Security Permit",
        "👨‍✈️ Forest Guide + Armed Guard for Protection",
        "🚐 Transport: Khulna ↔ Boat Boarding Point",
        "📸 Complimentary Photography + Drone Shots",
      ],
      additionalInfo: [
        "Prior Booking Required (Limited Cabins)",
        "Group & Family Friendly",
        "Moderate Physical Activity (Forest Walks, Boat Transfer)",
        "Light Bag with Essentials Recommended",
      ],
    },
    additionalInfo: [
      "🔘 Call: 01898-334722 / 01898-334733",
      "📧 Email: info.royalsafaritours@gmail.com",
      "📍 Office: Khilgaon, Dhaka",
      "🌐 Facebook",
    ],
  },

  {
    id: 17,
    image:
      "/images/tour-package/nepal/534375987_122223586604252080_6381032114163550414_n.webp",
    title: "Chitwan ",
    category: "nepal",
    price: "41,200",
    rating: 5,
    duration: "7 Days & 6 Nights",
    description: {
      details:
        "Ready to explore the wild side of Nepal? Embark on a once-in-a-lifetime safari adventure through Chitwan National Park, home to rhinos, elephants, Bengal tigers, and exotic birdlife. This Nepal Golden Triangle package blends the thrill of the jungle with serene landscapes and authentic cultural experiences. Perfect for wildlife lovers, adventure seekers, and nature photographers!",
      tripIncludes: [
        "🚐 Inter-City & Local Transfers",
        "🏨 Hotel Stays (Standard Category)",
        "🍳 Daily Breakfast at Hotel",
        "🚙 Jungle Jeep Safari through Chitwan",
        "🦜 Bird Watching & Nature Walks",
        "🧭 Local Guide for Safari & City Activities",
        "🧳 Luggage Handling Assistance",
      ],
      additionalInfo: [
        "✈️ Flights Not Included (Arranged on Request)",
        "🛂 No Visa Required for Bangladeshi Citizens",
        "📷 Optional Add-on: Travel Photography",
        "🍽️ Lunch/Dinner Available at Extra Cost",
        "👥 Twin Sharing Basis",
        "📦 EMI Payment Option Available",
      ],
    },
    additionalInfo: [
      "✅ Original Passport Minimum 7 Months Validity.",
      "✅ 48mm x 33mm, 1 Copy Photo. (May vary based on Nation)",
      "✅ Bank statement and solvency certificate for last 6 months. Balance Minimum BDT. 3,00,000/- .",
      "✅ NOC for Service Holder.",
      "✅ Office ID card for Job Holder.",
      "✅ Confirmed Air Ticket",
    ],
  },
  {
    id: 18,
    image:
      "/images/tour-package/nepal/534385004_122223586550252080_2024382614783009837_n.webp",
    title: "Pokhara & Kathmandu",
    category: "nepal",
    price: "32,500",
    rating: 5,
    duration: "6 Days & 5 Nights",
    description: {
      details:
        "Need a refreshing break? Head to Nepal’s charming hills and serene valleys with this all-in-one package covering Pokhara and Kathmandu. From sunrise at Sarangkot to sightseeing in the ancient city of temples, this tour offers a balanced mix of nature, culture, and relaxation. Perfect for families, couples, and laid-back travelers seeking peace and perspective.",
      tripIncludes: [
        "🚐 Inter-City & Local Transport",
        "🏨 Hotel Stay in Pokhara & Kathmandu (Standard Category)",
        "🍳 Daily Breakfast at Hotel",
        "🧭 Sightseeing Tours:",
        " • Pokhara: Phewa Lake, Davis Falls, Sarangkot Sunrise",
        " • Kathmandu: Swayambhunath, Durbar Square, Pashupatinath",
        "🧳 Luggage Support",
        "👨‍✈️ Bangla/English-Speaking Tour Guide",
      ],
      additionalInfo: [
        "✈️ Flights Not Included (Can be arranged separately)",
        "🛂 No Visa Required for Bangladeshi Citizens",
        "🍽️ Lunch/Dinner Not Included (Available at Extra Cost)",
        "👥 Twin Sharing Basis",
        "📦 EMI Payment Option Available",
      ],
    },
    additionalInfo: [
      "✅ Original Passport Minimum 7 Months Validity.",
      "✅ 48mm x 33mm, 1 Copy Photo. (May vary based on Nation)",
      "✅ Bank statement and solvency certificate for last 6 months. Balance Minimum BDT. 3,00,000/- .",
      "✅ NOC for Service Holder.",
      "✅ Office ID card for Job Holder.",
      "✅ Confirmed Air Ticket",
    ],
  },
  {
    id: 19,
    image:
      "/images/tour-package/nepal/534593861_122223586556252080_3339348182590477302_n.webp",
    title: "Kathmandu, Pokhara & Nagarkot",
    category: "nepal",
    price: "29,900",
    rating: 5,
    duration: "5 Days & 4 Nights",
    description: {
      details:
        "Can't decide between Kathmandu's culture, Pokhara's lakes, or Nagarkot's mountain sunrise? With this all-in-one package, you don’t have to. Royal Safari combines the top highlights of all three destinations into a single, seamless experience across Nepal’s scenic valleys and sacred heritage.Perfect for first-timers, cultural explorers, and mountain lovers!",
      tripIncludes: [
        "🚐 Inter-City Transport & Local Transfers",
        "🏨 4 Nights Hotel Stay (Standard Category)",
        "🍽️ Daily Breakfast at Hotel",
        "🧭 Sightseeing Tours:",
        " • Kathmandu: Pashupatinath, Durbar Square, Swayambhunath",
        " • Pokhara: Davis Falls, Phewa Lake, Mahendra Cave",
        " • Nagarkot: Sunrise View & Mountain Lookout",
        "🧳 Luggage Handling",
        "👨‍✈️ English/Bangla Speaking Tour Guide",
      ],
      additionalInfo: [
        "✈️ Flights Not Included (Can Be Arranged on Request)",
        "🛂 No Visa Required for Bangladeshi Nationals",
        "🍴 Lunch & Dinner Not Included",
        "👥 Twin Sharing Basis",
        "📦 EMI Support Available",
      ],
    },
    additionalInfo: [
      "✅ Original Passport Minimum 7 Months Validity.",
      "✅ 48mm x 33mm, 1 Copy Photo. (May vary based on Nation)",
      "✅ Bank statement and solvency certificate for last 6 months. Balance Minimum BDT. 3,00,000/- .",
      "✅ NOC for Service Holder.",
      "✅ Office ID card for Job Holder.",
      "✅ Confirmed Air Ticket",
    ],
  },
  {
    id: 20,
    image:
      "/images/tour-package/thailand/497708993_122208162362252080_6763226045674536060_n.webp",
    title: "PATTAYA",
    category: "thailand",
    price: "56,000",
    rating: 5,
    duration: "4 Days & 3 Nights",
    description: {
      details:
        "Soak in the sun, sea, and vibrant nightlife of Pattaya, Thailand’s most exciting coastal city. From the tropical beauty of Coral Island to the buzzing Walking Street, this 4-day escape is crafted for beach lovers and thrill-seekers alike. Whether you're jet skiing in turquoise waters or enjoying cabaret shows after dark, Pattaya promises unforgettable memories. Perfect for couples, solo explorers, and friend groups looking to blend adventure with leisure.",
      tripIncludes: [
        "🏨 3 Nights Hotel Stay in Central Pattaya (Standard/Deluxe options)",
        "🚐 Airport Transfers (Suvarnabhumi ↔ Pattaya)",
        "🏝️ Full Day Coral Island Tour with Speedboat & Lunch",
        "🕺 Evening Alcazar Cabaret Show",
        "🍜 Daily Breakfast Buffet",
        "📸 Professional Trip Photography (optional)",
        "🧭 Bangla-Speaking Tour Guide",
        "🛃 Visa Assistance (Optional Add-on)",
      ],
      additionalInfo: [
        "Flights Not Included (Available on Request)",
        "Dual Sharing Room",
        "Visa Processing Time: 5–7 Working Days",
        "Minimum Group Size: 2 Pax",
        "EMI Available",
      ],
    },
    additionalInfo: [
      "✅ Original Passport Minimum 7 Months Validity.",
      "✅ 48mm x 33mm, 1 Copy Photo. (May vary based on Nation)",
      "✅ Bank statement and solvency certificate for last 6 months. Balance Minimum BDT. 3,00,000/- .",
      "✅ NOC for Service Holder.",
      "✅ Office ID card for Job Holder.",
      "✅ Confirmed Air Ticket",
    ],
  },
  {
    id: 21,
    image:
      "/images/tour-package/thailand/497806902_122208162440252080_939084642834134413_n.webp",
    title: "BANGKOK",
    category: "thailand",
    price: "59,000",
    rating: 5,
    duration: "5 Days & 5 Nights",
    description: {
      details:
        "Bangkok the vibrant heart of Thailand is a perfect blend of ancient culture and modern marvels. From majestic temples and floating markets to luxury malls and legendary street food, this city never sleeps. Whether you're a first-time explorer or returning for more, this trip is curated to give you the best of Bangkok. Perfect for couples, solo adventurers, and shopaholics alike!",
      tripIncludes: [
        "🏨 4 Nights Hotel Stay (3–4 Star Category)",
        "🚐 Airport Transfers & Daily Transport",
        "🕌 City Tour covering Grand Palace, Wat Arun & More",
        "🛍️ Shopping at MBK, Siam Paragon & Chatuchak",
        "🍜 Street Food Walk Experience (Optional Add-on)",
        "🧭 English/Bangla-Speaking Tour Guide",
        "🧳 Luggage Handling & Travel Tips",
        "📸 Free Travel Photography Session",
      ],
      additionalInfo: [
        "✈️ Flights Excluded (Available Upon Request)",
        "🍽️ Daily Breakfast Included",
        "🛂 Visa Assistance Available",
        "👥 Twin Sharing Accommodation",
        "📦 EMI Support Available",
      ],
    },
    additionalInfo: [
      "✅ Original Passport Minimum 7 Months Validity.",
      "✅ 48mm x 33mm, 1 Copy Photo. (May vary based on Nation)",
      "✅ Bank statement and solvency certificate for last 6 months. Balance Minimum BDT. 3,00,000/- .",
      "✅ NOC for Service Holder.",
      "✅ Office ID card for Job Holder.",
      "✅ Confirmed Air Ticket",
    ],
  },
  {
    id: 22,
    image:
      "/images/tour-package/thailand/497840049_122208162494252080_2849204271938585146_n.webp",
    title: "CORAL ISLAND",
    category: "thailand",
    price: "6,900",
    rating: 5,
    duration: "Day Tour (9 AM – 5 PM)",
    description: {
      details:
        "A tropical paradise just off the coast of Pattaya, Coral Island (Koh Larn) is perfect for a beach lover's dream day. Crystal-clear waters, coral reefs, golden sands, and thrilling water sports make it a must-visit destination on your Thailand itinerary. Whether you’re looking to relax or explore, this tour is curated for both. Ideal for solo travelers, couples, friends, or family groups!",
      tripIncludes: [
        "🚤 Speedboat Transfer to Coral Island",
        "🏖️ Guided Beach Hopping (Tien Beach, Samae Beach, etc.)",
        "🌊 Snorkeling & Banana Boat (Optional Add-ons)",
        "🍛 Thai Buffet Lunch by the Beach",
        "🧭 English-Speaking Tour Leader",
        "📸 Complimentary Tour Photography",
        "🧳 Locker & Shower Facilities",
        "⛑️ Basic Safety & Life Jackets Provided",
      ],
      additionalInfo: [
        "🚌 Pickup/Drop-off from Pattaya Hotel",
        "🛂 No Passport Needed (for Coral Island)",
        "📦 Full Day Excursion",
        "🎒 Light Dress Code & Sun Protection Recommended",
        "🛍️ Souvenir Stalls Available on Island",
      ],
    },
    additionalInfo: [
      "✅ Original Passport Minimum 7 Months Validity.",
      "✅ 48mm x 33mm, 1 Copy Photo. (May vary based on Nation)",
      "✅ Bank statement and solvency certificate for last 6 months. Balance Minimum BDT. 3,00,000/- .",
      "✅ NOC for Service Holder.",
      "✅ Office ID card for Job Holder.",
      "✅ Confirmed Air Ticket",
    ],
  },
];
